FROM qmcgaw/latexdevcontainer
RUN tlmgr install biblatex && \
    tlmgr install biber && \
    tlmgr install easyreview && \
    tlmgr install soul && \
    tlmgr install xcolor && \
    tlmgr install todonotes